[tools]
ruby = "latest"

[tasks.update]
description = "Update packages"
run = ["bundle update", "bundle leak update", "touch tmp/restart.txt"]

[tasks.install]
description = "Install packages"
run = ["bundle install"]

[tasks.lint]
description = "Run linters"
run = [
  "bundle exec rubocop -A",
  "bundle exec i18n-tasks normalize",
  "bundle leak",
]

[tasks.test]
description = "Run tests in parallel (fast)"
run = [
  "bundle exec parallel_rspec spec/", 
  ]

[tasks."test:serial"]
description = "Run tests serially (for debugging)"
run = [
  "bundle exec rspec", 
  ]

[tasks.dev]
description = "Run development server"
run = ["./bin/dev"]

[tasks.debug]
description = "Run debug server"
run = ["rdbg -n --open=vscode -c -- bin/rails s "]

[tasks.audit]
description = "Run security audit"
run = ["bundle audit", "osv-scanner scan source -r ."]

[tasks.db-create]
description = "Prepare development database"
run = [
  "bundle exec rails db:create",
  "bundle exec rails db:migrate",
  "bundle exec rails db:prepare",
  "bundle exec rails db:seed",
  "rails parallel:create"
]

[tasks.db-drop]
description = "Destroy development database"
run = [
  "bundle exec rails db:drop",
  "rails parallel:drop"
]

[tasks.restart]
description = "Restart server"
run = "touch tmp/restart.txt"
