def setup_rubocop_dev_env
  environment 'config.generators.apply_rubocop_autocorrect_after_generate!', env: "development"
  environment '# Apply autocorrection by RuboCop to files generated by `bin/rails generate`.', env: "development"
end
