name: Danger

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Run Auto assign
        uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} # sets in repo settings/secrets
          configuration-path: .github/auto_assign.yml
      - name: Run brakeman with reviewdog
        uses: reviewdog/action-brakeman@v1
        with:
          brakeman_flags: --color
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
      - name: Run Danger
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # sets in repo settings/secrets
