# frozen_string_literal: true

brew "act"
brew "gh"
brew "imagemagick"
brew "jq"
brew "lefthook"
brew "mise"
brew "neovim"
brew "osv-scanner"
brew "pgcli"
brew "vips"
brew "xh"
brew "zellij"

cask "wezterm"
cask "postgres-unofficial"
