Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'config/application.rb'

Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - 'spec/factories/users.rb'

Metrics/AbcSize: 
  Enabled: true
  Exclude:
    - 'app/controllers/application_controller.rb'

Layout/LineLength:
  Enabled: true
  Exclude:
    - 'features/step_definitions/email_steps.rb'