Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'config/application.rb'

Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - 'spec/factories/users.rb'

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Exclude:
    - 'features/step_definitions/email_steps.rb'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
